server:
  port: 8081
spring:
  application:
    name: catalog-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/factoryx
    username: factory
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

grpc:
  server:
    port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
