#App
spring:
  application:
    name: fx-gateway
  zipkin:
    enabled: false
    base-url: http://localhost:9411

server:
  port: 9090

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

#Logs
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

#Routes
spring.cloud.gateway.routes:
  - id: order-service
    uri: lb://order-service
    predicates:
      - Path=/order-service/**
  - id: product-service
    uri: lb://product-service
    predicates:
      - Path=/order/**
  - id: eureka-ui
    uri: http://localhost:8761
    predicates:
      - Path=/eurekawebui
  - id: eureka-css-js
    uri: http://localhost:8761
    predicates:
      - Path=/eureka/**