apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: factory-x
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: gcr.io/factory-x/order-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/factoryx
            - name: SPRING_DATASOURCE_USERNAME
              value: factory
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: GRPC_CLIENT_CATALOG_SERVICE_ADDRESS
              value: static://catalog-service:9090
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: factory-x
spec:
  selector:
    app: order-service
  ports:
    - port: 8082
      targetPort: 8082
      name: http
